### ISSUE TITLE
How to install and use it in ionic 3 ?

### ISSUE THREAD

**Issue by juliofihdeldev** [vasani-arpit/cordova-plugin-downloadmanager#8]

**Comment by vasani-arpit** [comment]
for the intallation it would be like

```
cordova plugin add https://github.com/vasani-arpit/cordova-plugin-downloadmanager
```

As far as usability goes plugin should be available  in `cordova.plugin` object after device is ready.

**Comment by vasani-arpit** [comment]
Re-open if you have a query.

**Comment by juliofihdeldev** [comment]
Thank you


Le dim. 10 févr. 2019 à 03:48, Arpit Vasani <notifications@github.com> a
écrit :

**Comment by vasani-arpit** [comment]
You are welcome :)
